#!/bin/bash

psql $DATABASE_URL -c \
"CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS catalog;
CREATE SCHEMA IF NOT EXISTS search;
CREATE SCHEMA IF NOT EXISTS scaffolder;
CREATE SCHEMA IF NOT EXISTS techdocs;
CREATE SCHEMA IF NOT EXISTS proxy;
CREATE SCHEMA IF NOT EXISTS permission;
CREATE SCHEMA IF NOT EXISTS app;"
